#!/bin/bash
# Google Cloud Infrastructure Setup Script
# This script sets up initial GCP infrastructure

set -e  # Exit on error

PROJECT_ID=$(gcloud config get-value project 2>/dev/null)
REGION="us-central1"

if [ -z "$PROJECT_ID" ]; then
  echo "❌ No project set. Run: gcloud config set project YOUR_PROJECT_ID"
  exit 1
fi

echo "🚀 Setting up Google Cloud infrastructure for Foodism API..."
echo "📋 Project: $PROJECT_ID"
echo "📍 Region: $REGION"
echo ""

# Enable required APIs
echo "🔌 Enabling required APIs..."
gcloud services enable \
  compute.googleapis.com \
  sqladmin.googleapis.com \
  run.googleapis.com \
  cloudbuild.googleapis.com \
  vpcaccess.googleapis.com \
  --quiet

echo "✅ APIs enabled"
echo ""

# Create Cloud SQL instance
echo "🗄️  Creating Cloud SQL PostgreSQL instance..."
echo "This will take 5-10 minutes..."

DB_EXISTS=$(gcloud sql instances describe foodism-db 2>/dev/null || echo "not found")

if [ "$DB_EXISTS" == "not found" ]; then
  echo "Enter database root password (min 8 characters):"
  read -s DB_PASSWORD
  
  if [ ${#DB_PASSWORD} -lt 8 ]; then
    echo "❌ Password must be at least 8 characters"
    exit 1
  fi
  
  gcloud sql instances create foodism-db \
    --database-version=POSTGRES_15 \
    --tier=db-f1-micro \
    --region=$REGION \
    --root-password="$DB_PASSWORD" \
    --storage-type=SSD \
    --storage-size=20GB \
    --storage-auto-increase \
    --backup-start-time=03:00
  
  echo "✅ Cloud SQL instance created"
else
  echo "ℹ️  Cloud SQL instance already exists"
  echo "Enter database root password:"
  read -s DB_PASSWORD
fi

# Create database
echo "📊 Creating database..."
gcloud sql databases create foodism_db \
  --instance=foodism-db \
  2>/dev/null && echo "✅ Database created" || echo "ℹ️  Database already exists"

# Create database user
echo "👤 Creating database user..."
gcloud sql users create foodism_user \
  --instance=foodism-db \
  --password="$DB_PASSWORD" \
  2>/dev/null && echo "✅ User created" || echo "ℹ️  User already exists (updating password)"
  
# Update password if user exists
gcloud sql users set-password foodism_user \
  --instance=foodism-db \
  --password="$DB_PASSWORD" \
  --quiet 2>/dev/null || true

# Get connection name
CONNECTION_NAME=$(gcloud sql instances describe foodism-db \
  --format='value(connectionName)')

# Create VPC connector for Cloud Run
echo "🔗 Creating VPC connector..."
gcloud compute networks vpc-access connectors create foodism-connector \
  --region=$REGION \
  --network=default \
  --range=10.8.0.0/28 \
  --min-instances=2 \
  --max-instances=3 \
  2>/dev/null && echo "✅ VPC connector created" || echo "ℹ️  VPC connector already exists"

# Grant Cloud Run service account access
SERVICE_ACCOUNT=$(gcloud projects describe $PROJECT_ID \
  --format='value(projectNumber)')-compute@developer.gserviceaccount.com

echo "🔐 Granting Cloud SQL access to service account..."
gcloud projects add-iam-policy-binding $PROJECT_ID \
  --member="serviceAccount:$SERVICE_ACCOUNT" \
  --role="roles/cloudsql.client" \
  --quiet > /dev/null

# Create output file
cat > gcp-infrastructure.env << EOF
# Google Cloud Infrastructure Configuration
# Generated by setup-gcp.sh on $(date)

PROJECT_ID=$PROJECT_ID
REGION=$REGION
CONNECTION_NAME=$CONNECTION_NAME
DB_PASSWORD=$DB_PASSWORD
SERVICE_ACCOUNT=$SERVICE_ACCOUNT
EOF

echo ""
echo "✅ Google Cloud infrastructure setup complete!"
echo ""
echo "📝 Configuration saved to: gcp-infrastructure.env"
echo ""
echo "Connection Details:"
echo "  Connection Name: $CONNECTION_NAME"
echo "  Database: foodism_db"
echo "  User: foodism_user"
echo ""
echo "Next steps:"
echo "  1. Deploy to Cloud Run:"
echo "     cd server"
echo "     gcloud builds submit --tag gcr.io/$PROJECT_ID/foodism-api"
echo "     gcloud run deploy foodism-api \\"
echo "       --image gcr.io/$PROJECT_ID/foodism-api \\"
echo "       --add-cloudsql-instances=$CONNECTION_NAME \\"
echo "       --set-env-vars=\"DB_TYPE=postgresql,DB_NAME=foodism_db,DB_USER=foodism_user,DB_PASSWORD=$DB_PASSWORD,DB_HOST=/cloudsql/$CONNECTION_NAME\""
echo ""
echo "See GOOGLE_CLOUD_DEPLOYMENT_GUIDE.md for complete instructions."

