#!/bin/bash
# AWS Infrastructure Setup Script
# This script creates security groups and sets up the initial AWS infrastructure

set -e  # Exit on error

PROJECT_NAME="foodism-api"
REGION="us-east-1"

echo "🚀 Setting up AWS infrastructure for Foodism API..."

# Get default VPC
echo "📡 Getting default VPC..."
VPC_ID=$(aws ec2 describe-vpcs \
  --filters "Name=isDefault,Values=true" \
  --query "Vpcs[0].VpcId" \
  --output text)

if [ -z "$VPC_ID" ] || [ "$VPC_ID" == "None" ]; then
  echo "❌ No default VPC found. Please specify a VPC ID."
  exit 1
fi

echo "✅ Found VPC: $VPC_ID"

# Create API Security Group
echo "🔒 Creating API Security Group..."
API_SG_ID=$(aws ec2 create-security-group \
  --group-name ${PROJECT_NAME}-api-sg \
  --description "Security group for Foodism API server" \
  --vpc-id $VPC_ID \
  --query 'GroupId' \
  --output text 2>/dev/null || \
  aws ec2 describe-security-groups \
    --filters "Name=group-name,Values=${PROJECT_NAME}-api-sg" "Name=vpc-id,Values=$VPC_ID" \
    --query "SecurityGroups[0].GroupId" \
    --output text)

echo "✅ API Security Group: $API_SG_ID"

# Create Database Security Group
echo "🔒 Creating Database Security Group..."
DB_SG_ID=$(aws ec2 create-security-group \
  --group-name ${PROJECT_NAME}-db-sg \
  --description "Security group for Foodism RDS database" \
  --vpc-id $VPC_ID \
  --query 'GroupId' \
  --output text 2>/dev/null || \
  aws ec2 describe-security-groups \
    --filters "Name=group-name,Values=${PROJECT_NAME}-db-sg" "Name=vpc-id,Values=$VPC_ID" \
    --query "SecurityGroups[0].GroupId" \
    --output text)

echo "✅ Database Security Group: $DB_SG_ID"

# Configure API Security Group Rules
echo "🔧 Configuring API Security Group rules..."

# Check if rules already exist (idempotent)
HTTP_EXISTS=$(aws ec2 describe-security-groups \
  --group-ids $API_SG_ID \
  --query "SecurityGroups[0].IpPermissions[?FromPort==\`80\` && ToPort==\`80\`]" \
  --output text)

if [ -z "$HTTP_EXISTS" ]; then
  aws ec2 authorize-security-group-ingress \
    --group-id $API_SG_ID \
    --protocol tcp \
    --port 80 \
    --cidr 0.0.0.0/0 > /dev/null
  echo "  ✅ Added HTTP (port 80) rule"
else
  echo "  ℹ️  HTTP rule already exists"
fi

HTTPS_EXISTS=$(aws ec2 describe-security-groups \
  --group-ids $API_SG_ID \
  --query "SecurityGroups[0].IpPermissions[?FromPort==\`443\` && ToPort==\`443\`]" \
  --output text)

if [ -z "$HTTPS_EXISTS" ]; then
  aws ec2 authorize-security-group-ingress \
    --group-id $API_SG_ID \
    --protocol tcp \
    --port 443 \
    --cidr 0.0.0.0/0 > /dev/null
  echo "  ✅ Added HTTPS (port 443) rule"
else
  echo "  ℹ️  HTTPS rule already exists"
fi

# Add SSH from current IP
YOUR_IP=$(curl -s https://checkip.amazonaws.com)
SSH_EXISTS=$(aws ec2 describe-security-groups \
  --group-ids $API_SG_ID \
  --query "SecurityGroups[0].IpPermissions[?FromPort==\`22\` && ToPort==\`22\` && IpRanges[?CidrIp==\`${YOUR_IP}/32\`]]" \
  --output text)

if [ -z "$SSH_EXISTS" ]; then
  aws ec2 authorize-security-group-ingress \
    --group-id $API_SG_ID \
    --protocol tcp \
    --port 22 \
    --cidr ${YOUR_IP}/32 > /dev/null
  echo "  ✅ Added SSH (port 22) from your IP: $YOUR_IP"
else
  echo "  ℹ️  SSH rule already exists"
fi

# Configure Database Security Group Rules
echo "🔧 Configuring Database Security Group rules..."

# Allow PostgreSQL from API security group
PG_EXISTS=$(aws ec2 describe-security-groups \
  --group-ids $DB_SG_ID \
  --query "SecurityGroups[0].IpPermissions[?FromPort==\`5432\` && ToPort==\`5432\` && UserIdGroupPairs[?GroupId==\`${API_SG_ID}\`]]" \
  --output text)

if [ -z "$PG_EXISTS" ]; then
  aws ec2 authorize-security-group-ingress \
    --group-id $DB_SG_ID \
    --protocol tcp \
    --port 5432 \
    --source-group $API_SG_ID > /dev/null
  echo "  ✅ Added PostgreSQL (port 5432) from API security group"
else
  echo "  ℹ️  PostgreSQL rule already exists"
fi

# Create output file with IDs
cat > aws-infrastructure.env << EOF
# AWS Infrastructure Configuration
# Generated by setup-aws.sh on $(date)

VPC_ID=$VPC_ID
API_SECURITY_GROUP_ID=$API_SG_ID
DB_SECURITY_GROUP_ID=$DB_SG_ID
REGION=$REGION
PROJECT_NAME=$PROJECT_NAME
EOF

echo ""
echo "✅ AWS infrastructure setup complete!"
echo ""
echo "📝 Configuration saved to: aws-infrastructure.env"
echo ""
echo "Security Groups:"
echo "  API Security Group ID:  $API_SG_ID"
echo "  Database Security Group ID: $DB_SG_ID"
echo ""
echo "Next steps:"
echo "  1. Create RDS instance:"
echo "     aws rds create-db-instance --db-instance-identifier ${PROJECT_NAME}-db \\"
echo "       --db-instance-class db.t3.micro --engine postgres \\"
echo "       --master-username admin --master-user-password 'YOUR_PASSWORD' \\"
echo "       --allocated-storage 20 --vpc-security-group-ids $DB_SG_ID"
echo ""
echo "  2. Create EC2 instance:"
echo "     aws ec2 run-instances --image-id ami-xxx --instance-type t3.micro \\"
echo "       --security-group-ids $API_SG_ID --key-name your-key-pair"
echo ""
echo "See AWS_DEPLOYMENT_GUIDE.md for complete instructions."

